services:
  - type: web
    name: sklep-studia
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn sklep_studia.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sklep_studia.settings
      - key: PYTHON_VERSION
        value: 3.10
